In [1]:
import pandas as pd
import altair as alt
alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [2]:
dataq1_1 = pd.read_csv('../../data/data_Q1-1.csv')
dataq1_2 = pd.read_csv('../../data/data_Q1-2.csv')

In [3]:
dataq1_1

,character,word_count,image
0,Homer,278537.0,https://img.icons8.com/doodle/48/homer-simpson...
1,Marge,127189.0,https://img.icons8.com/doodle/48/marge-simpson...
2,Bart,112605.0,https://img.icons8.com/doodle/48/bart-simpson.png
3,Lisa,101793.0,https://img.icons8.com/doodle/48/lisa-simpson.png
4,Mr. Burns,37713.0,https://img.icons8.com/doodle/48/charles-montg...
5,Moe,34260.0,https://img.icons8.com/doodle/48/bartender-mo.png
6,Flanders,26918.0,https://img.icons8.com/doodle/48/ned-flanders.png
7,Krusty,21607.0,https://img.icons8.com/doodle/48/krusty-the-cl...
8,Chief Wiggum,20910.0,https://img.icons8.com/doodle/48/clancy-wiggum...
9,Grampa,20541.0,https://img.icons8.com/doodle/48/abraham-simps...
10,Brockman,16538.0,https://static.simpsonswiki.com/images/3/35/Ta...
11,Milhouse,15696.0,https://img.icons8.com/doodle/48/milhouse-van-...
12,Apu,11838.0,https://static.simpsonswiki.com/images/0/08/Ta...
13,Lenny,10270.0,https://static.simpsonswiki.com/images/6/6f/Ta...
14,Smithers,9762.0,https://static.simpsonswiki.com/images/3/3a/Ta...
15,Nelson,8836.0,https://static.simpsonswiki.com/images/0/0c/Ta...
16,Dr. Hibbert,7950.0,https://static.simpsonswiki.com/images/d/d5/Ta...
17,Edna Krabappel,7820.0,https://static.simpsonswiki.com/images/1/14/Ta...
18,Carl,7518.0,https://static.simpsonswiki.com/images/a/a4/Ta...
19,Rev. Lovejoy,7045.0,https://static.simpsonswiki.com/images/4/40/Ta...
20,Sideshow Bob,6462.0,https://static.simpsonswiki.com/images/6/68/Ta...
21,Mayor Quimby,6340.0,https://static.simpsonswiki.com/images/e/e3/Ta...
22,Comic Book Guy,5932.0,https://static.simpsonswiki.com/images/a/a9/Ta...
23,Chalmers,5767.0,https://static.simpsonswiki.com/images/5/58/Ta...
24,Professor Frink,5384.0,https://static.simpsonswiki.com/images/0/09/Ta...
25,Groundskeeper Willie,5086.0,https://static.simpsonswiki.com/images/4/40/Ta...
26,Selma,5067.0,https://static.simpsonswiki.com/images/8/8f/Ta...
27,Barney,4647.0,https://img.icons8.com/doodle/48/barney-gumble...
28,Patty,3910.0,https://static.simpsonswiki.com/images/3/31/Ta...
29,Martin Prince,3845.0,https://static.simpsonswiki.com/images/d/da/Ta...
30,Lou,3728.0,https://static.simpsonswiki.com/images/c/cf/Ta...
31,Otto,3615.0,https://static.simpsonswiki.com/images/4/48/Ta...
32,Sideshow Mel,3391.0,https://static.simpsonswiki.com/images/6/6d/Ta...
33,Fat Tony,3108.0,https://static.simpsonswiki.com/images/1/1b/Ta...
34,Ralph,3104.0,https://img.icons8.com/doodle/48/ralf.png
35,Jimbo,2760.0,https://static.simpsonswiki.com/images/f/f3/Ta...
36,Kirk,2514.0,https://static.simpsonswiki.com/images/6/61/Ta...
37,Agnes Skinner,2478.0,https://static.simpsonswiki.com/images/b/b1/Ta...
38,Cletus,2401.0,https://static.simpsonswiki.com/images/a/a0/Ta...
39,Duffman,992.0,https://static.simpsonswiki.com/images/1/18/Ta...

In [4]:
dataq1_1_test = dataq1_1[dataq1_1['character'].isin(['Homer', 'Bart', 'Lisa', 'Marge', 'Apu'])]
dataq1_2_test = dataq1_2[dataq1_2['character'].isin(['Homer', 'Bart', 'Lisa', 'Marge', 'Apu'])]

In [5]:
dataq5_1 = pd.read_csv('../../data/data_Q5-1.csv')
dataq5_2 = pd.read_csv('../../data/data_Q5-2.csv')

In [6]:
dataq5_1_test = dataq5_1[dataq5_1['character'].isin(['Homer', 'Bart', 'Lisa', 'Marge', 'Apu'])]
dataq5_2_test = dataq5_2[dataq5_2['character'].isin(['Homer', 'Bart', 'Lisa', 'Marge', 'Apu'])]

In [7]:
dataq5_1_test

,character,sentence_count,image
0,Homer,28463,https://img.icons8.com/doodle/48/homer-simpson...
1,Marge,13393,https://img.icons8.com/doodle/48/marge-simpson...
2,Bart,13321,https://img.icons8.com/doodle/48/bart-simpson.png
3,Lisa,10964,https://img.icons8.com/doodle/48/lisa-simpson.png
13,Apu,1004,https://static.simpsonswiki.com/images/0/08/Ta...

# Q1

In [8]:
y_enc = alt.Y(
    "character:N",
    sort=dataq1_1_test['character'].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False, title=None),
 )

selector = alt.selection_point(
    fields=['character'], 
)

bars = alt.Chart(dataq1_1_test).mark_bar().encode(
    x=alt.X("word_count:Q", title="Total Word Count"),
    y=y_enc,
    tooltip= [alt.Tooltip("character:N", title="Character"), alt.Tooltip("word_count:Q", title="Total Word Count")],
    opacity=alt.when(selector).then(alt.value(1)).otherwise(alt.value(0.2)),

).add_params(selector)

flags = (
    alt.Chart(dataq1_1_test.assign(zero=0))
    .mark_image(width=25, height=25, clip=False, xOffset=-12)
    .encode(
        y=y_enc,
        x=alt.X("zero:Q"),
        url="image:N"
    )
)   
barplot_final = (bars + flags).properties(width=300,title = "Total Word Count per Character")

In [9]:
dataq1_2_test

     character  episode_id  word_count
92         Apu          12       101.0
93         Apu          26        79.0
94         Apu          27        35.0
95         Apu          29        11.0
96         Apu          31        46.0
...        ...         ...         ...
5952     Marge         564        90.0
5953     Marge         565       236.0
5954     Marge         566       228.0
5955     Marge         567        32.0
5956     Marge         568       450.0

[2450 rows x 3 columns]

In [10]:
gaussian_jitter = alt.Chart(dataq1_2_test, title='Word Count Distribution').mark_circle(size=8,).encode(
    y=y_enc,
    x=alt.X("word_count:Q", title="Word Count"),
    yOffset="jitter:Q",
    opacity=alt.when(selector).then(alt.value(0.8)).otherwise(alt.value(0.2))
).transform_calculate(
    jitter="sqrt(-2*log(random()))*cos(2*PI*random())"
).add_params(selector)

mean_bar = alt.Chart(dataq1_2_test).mark_tick(color='red', size=30,thickness=3).transform_aggregate(
    mean_wc="mean(word_count)",
    groupby=["character"]
).encode(
    x= alt.X("mean_wc:Q"),
    y=y_enc #
)
jitter_final = (gaussian_jitter + mean_bar).properties(width=300)
jitter_final

alt.LayerChart(...)

In [9]:
final_layout = alt.hconcat(
    barplot_final, 
    jitter_final
).configure_view(
    step=40 
).resolve_scale(
    y='shared' 
)

final_layout

/Users/bmantepe/Library/Python/3.12/lib/python/site-packages/IPython/core/interactiveshell.py:3579: UserWarning: Automatically deduplicated selection parameter with identical configuration. If you want independent parameters, explicitly name them differently (e.g., name='param1', name='param2'). See https://github.com/vega/altair/issues/3891
  exec(code_obj, self.user_global_ns, self.user_ns)

alt.HConcatChart(...)

# Q5

In [ ]:
dataq5_1_test

,character,sentence_count,image
0,Homer,28463,https://img.icons8.com/doodle/48/homer-simpson...
1,Marge,13393,https://img.icons8.com/doodle/48/marge-simpson...
2,Bart,13321,https://img.icons8.com/doodle/48/bart-simpson.png
3,Lisa,10964,https://img.icons8.com/doodle/48/lisa-simpson.png
13,Apu,1004,https://static.simpsonswiki.com/images/0/08/Ta...

In [ ]:
y_enc = alt.Y(
    "character:N",
    sort=dataq5_1_test['character'].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False, title=None),
 )

selector = alt.selection_point(
    fields=['character'], 
)

bars = alt.Chart(dataq5_1_test).mark_bar().encode(
    x=alt.X("sentence_count:Q", title="Total Sentence Count"),
    y=y_enc,
    tooltip= [alt.Tooltip("character:N", title="Character"), alt.Tooltip("sentence_count:Q", title="Total Sentence Count")],
    opacity=alt.when(selector).then(alt.value(1)).otherwise(alt.value(0.2))
).add_params(selector)

flags = (
    alt.Chart(dataq5_1_test.assign(zero=0))
    .mark_image(width=25, height=25, clip=False, xOffset=-12)
    .encode(
        y=y_enc,
        x=alt.X("zero:Q"),
        url="image:N"
    )
)

barplot_final = (bars + flags).properties(width=300,title = "Total Sentence Count per Character")

In [ ]:
gaussian_jitter = alt.Chart(dataq5_2_test, title='Sentence Count Distribution').mark_circle(size=8,).encode(
    y=y_enc,
    x=alt.X("sentence_count:Q", title="Sentence Count"),
    yOffset="jitter:Q",
    opacity=alt.when(selector).then(alt.value(0.8)).otherwise(alt.value(0.2))
).transform_calculate(
    jitter="sqrt(-2*log(random()))*cos(2*PI*random())"
).add_params(selector)

mean_bar = alt.Chart(dataq5_2_test).mark_tick(color='red', size=30,thickness=3).transform_aggregate(
    mean_sc="mean(sentence_count)",
    groupby=["character"]
).encode(
    x= alt.X("mean_sc:Q"),
    y=y_enc #
).transform_filter(selector)
jitter_final = (gaussian_jitter + mean_bar).properties(width=300)
jitter_final

alt.LayerChart(...)

In [1]:
final_layout = alt.hconcat(
    barplot_final, 
    jitter_final
).configure_view(
    step=40 
).resolve_scale(
    y='shared' 
)

final_layout

NameError: name 'alt' is not defined