In [12]:
import altair as alt
import pandas as pd

In [13]:
data = pd.read_csv('../../data/data_line_plot.csv')

In [14]:
data

,season,character,word_count,image
0,1,Agnes Skinner,49.0,https://static.simpsonswiki.com/images/b/b1/Ta...
1,1,Apu,101.0,https://static.simpsonswiki.com/images/0/08/Ta...
2,1,Barney,263.0,https://img.icons8.com/doodle/48/barney-gumble...
3,1,Bart,4902.0,https://img.icons8.com/doodle/48/bart-simpson.png
4,1,Brockman,215.0,https://static.simpsonswiki.com/images/3/35/Ta...
...,...,...,...,...
976,26,Rev. Lovejoy,140.0,https://static.simpsonswiki.com/images/4/40/Ta...
977,26,Selma,115.0,https://static.simpsonswiki.com/images/8/8f/Ta...
978,26,Sideshow Bob,31.0,https://static.simpsonswiki.com/images/6/68/Ta...
979,26,Sideshow Mel,136.0,https://static.simpsonswiki.com/images/6/6d/Ta...
980,26,Smithers,372.0,https://static.simpsonswiki.com/images/3/3a/Ta...

In [15]:
characters = ['Homer', 'Marge', 'Bart']

In [16]:
characters = ['Lou', 'Carl', 'Chief Wiggum']

In [17]:
data_filtered = data[data['character'].isin(characters)]

In [18]:
data_filtered

,season,character,word_count,image
5,1,Carl,30.0,https://static.simpsonswiki.com/images/a/a4/Ta...
6,1,Chief Wiggum,132.0,https://img.icons8.com/doodle/48/clancy-wiggum...
15,1,Lou,39.0,https://static.simpsonswiki.com/images/c/cf/Ta...
33,2,Carl,87.0,https://static.simpsonswiki.com/images/a/a4/Ta...
34,2,Chief Wiggum,15.0,https://img.icons8.com/doodle/48/clancy-wiggum...
...,...,...,...,...
911,25,Chief Wiggum,661.0,https://img.icons8.com/doodle/48/clancy-wiggum...
927,25,Lou,130.0,https://static.simpsonswiki.com/images/c/cf/Ta...
949,26,Carl,221.0,https://static.simpsonswiki.com/images/a/a4/Ta...
951,26,Chief Wiggum,466.0,https://img.icons8.com/doodle/48/clancy-wiggum...
964,26,Lou,90.0,https://static.simpsonswiki.com/images/c/cf/Ta...

afegir filtre de personatges amb st.multiselect

In [19]:
# lines_background = alt.Chart(data).mark_line(opacity=0.1,clip=True,strokeDash=[2,2]).encode(
#     x=alt.X('season:O', title='Season'),
#     y=alt.Y('word_count:Q', title='Total Word Count',scale = alt.Scale(domain=(0, max(data_filtered['word_count'])))),
#     color=alt.value('gray'),
#     detail =alt.Detail('character:N'),
#     tooltip=['season', 'character', 'word_count'],
# )

nearrest = alt.selection_point(nearest=True, on='mouseover', fields=['season'], empty=False)
selectors = alt.Chart(data_filtered).mark_point().encode(
    x='season:O',
    opacity=alt.value(0),
).add_params(nearrest)  

extra_selection = selection = alt.selection_point(fields=['character'], bind='legend')

lines_main = alt.Chart(data_filtered).mark_line(point=True).encode(
    x=alt.X('season:O', title='Season',),
    y=alt.Y('word_count:Q', title='Total Word Count',scale = alt.Scale(domain=(0, max(data_filtered['word_count'])))),
    tooltip=['image','season', 'word_count'],
    color = alt.Color('character:N', legend=alt.Legend(title="Character")),
    opacity=alt.when(selection).then(alt.value(1)).otherwise(alt.value(0.2))
).add_params(nearrest,extra_selection)

text = lines_main.mark_text(align='left', dx=10, dy=-15).encode(
    text=alt.condition(nearrest, 'word_count:N', alt.value(''))
)

images_point = alt.Chart(data_filtered).mark_image(width=30, height=30, align='center', baseline='middle').encode(
    x='season:O',
    y='word_count:Q',
    url='image:N'
).transform_filter(nearrest,extra_selection)

rules = alt.Chart(data).mark_rule(color='gray').encode(
    x='season:O',
).transform_filter(nearrest,extra_selection)

alt.layer(selectors, lines_main, text, rules, images_point).properties(
    width=600,
    height=400,
    title='Total Word Count per Season for Main Characters').configure_axisX(labelAngle=0)

alt.LayerChart(...)