In [38]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [39]:
data = pd.read_csv('../data/simpsons_script_lines.csv')

# 1. Filtering Speaking Lines

we detect that speaking line should be a boolean, but it's not as we have lower case intances, correct the dtype

In [40]:
data['speaking_line'] = data['speaking_line'].replace({'false': False, 'true': True}).astype(bool)

we detect that instances with speaking line = false refer to two narration, sounds of objects of the show (no character associated) or onomatopeias from the characters.
This instances won't hlp us analyzing the words of the characters and therefore we decide to delete them from the dataset to reduce it's size and keep only relevenat instances.
Since the column will be a constant after this filter, we delete it too.

In [41]:
data = data[data['speaking_line']]
data.drop(columns=['speaking_line'], inplace=True)

# 2 Incorrect Word Counts

we notice thah there are 10 incorrect rows, where the spoken words have a different format, the normalized_text is not a sequence of word, but an integer abd the word_count is true instead of an integer.
Most of this lines belong to non-main characters ot groups like 'Entire Town', singers or others.
There are a few of them that belong to the singer tonny bennet. Even though the character exists these and appears to say :Hey, good to see you these lines belong to the background song of the epsiode(https://www.youtube.com/watch?v=dZsOHz1z7Pc). Since tony bennet only says one line and the other ones are not conversation lines, we decide to rease all instances of tonny bennet.
We delte the instances from 'entire town', singers and Revue Cast Members, too, since they don't belong to individual characters and have very little represntation on the entirity of the dataset.

Moe Szyslak: "The reason I left you is simple:

In [42]:
data[data['word_count'] == 'true']

,id,episode_id,number,raw_text,timestamp_in_ms,character_id,location_id,raw_character_text,raw_location_text,spoken_words,normalized_text,word_count
8082,17667,59,87,"Singers: (SINGING) ""IT'S THE FIRST ANNUAL MONT...",442000,276.0,636.0,Singers,Springfield Civic Center,IT'S THE FIRST ANNUAL MONTGOMERY BURNS/ AWARD ...,455000,true
71799,81724,282,279,"Revue Cast Members: ""WE'RE THE PERFORMERS YOU ...",1068000,3510.0,2370.0,Revue Cast Members,Branson Theater,WE'RE THE PERFORMERS YOU THOUGHT WERE DEAD / L...,1075000,true
81136,91095,315,284,"Homer Simpson: ""I-M-O--",1220000,2.0,5.0,Homer Simpson,Simpson Home,"""I-M-O--,i-m-o--,1\n91096,315,285,Homer Simpso...",1220000,true
115436,125627,445,216,"Moe Szyslak: ""The reason I left you is simple:",1095000,17.0,15.0,Moe Szyslak,Moe's Tavern,"""The reason I left you is simple:,the reason i...",1095000,true
153015,4260,14,252,"Entire Town: ""SLEIGH BELLS RING / ARE YOU LIST...",1121000,241,211.0,Entire Town,NEIGHBORHOOD,"""SLEIGH BELLS RING / ARE YOU LISTENIN'/,sleigh...",1134000,true
154078,5345,18,199,"Tony Bennett: ""THERE'S A SWINGIN' TOWN I KNOW /",993000,297,239.0,Tony Bennett,Capital City,"THERE'S A SWINGIN' TOWN I KNOW /,theres a swin...",997000,true
154080,5348,18,202,"Tony Bennett: ""PEOPLE STOP AND SCREAM HELLO /",1001000,297,239.0,Tony Bennett,Capital City,"PEOPLE STOP AND SCREAM HELLO /,people stop and...",1004000,true
154082,5351,18,205,"Tony Bennett: ""IT'S THE KIND OF PLACE THAT MAKES",1009000,297,239.0,Tony Bennett,Capital City,"IT'S THE KIND OF PLACE THAT MAKES,its the kind...",1009000,true
154084,5354,18,208,"Tony Bennett: ""AND IT MAKES A KING FEEL LIKE/",1016000,297,239.0,Tony Bennett,Capital City,"AND IT MAKES A KING FEEL LIKE/,and it makes a ...",1019000,true
156870,8152,28,13,"Gulliver Dark: (SINGING) ""THE RULES THAT CONST...",115000,187,332.0,Gulliver Dark,Aztec Theater,THE RULES THAT CONSTRAIN OTHER MEN / MEAN NOTH...,125000,true

In [43]:
data = data[~data['raw_character_text'].isin(['Tony Bennett','Singers','Revue Cast Members','Entire Town'])]

This error comes from the transcription of the sentcne I am okay as initials I.M.O.K (Disney's subtitles also show the same)
This is actually the end of the previous sentence and not a new one. We will delete this sentence and add the correct normalized ending to the previous one and delete the incorrect one.

Also the sentence Homer says afterwards is lost. He says_  'get it? I am okay'. We will assing this sentence to the current incorrect one

In [44]:
current_sentence = 'last weeks garbage i missed the pick-up date but it doesnt matter because my mom is alive see'
missing_part = 'i am okay'
correct_sentence = current_sentence + ' ' + missing_part
word_count = len(correct_sentence.split())
data.loc[data["id"] == 91094, "word_count"] = word_count
data.loc[data["id"] == 91094, "normalized_text"] = correct_sentence

lost_sentence = 'get it i am okay'
word_count = len(lost_sentence.split())
data.loc[data["id"] == 91095, "word_count"] = word_count
data.loc[data["id"] == 91095, "normalized_text"] = lost_sentence

Moe's sentence error is also fixable, there is a missing part. 
The correct sentence is :  "The reason I left you is simple: I'm gay
We'll correct it on the data

In [45]:
correct_sentence = 'the reason i left you is simple im gay'
word_count = len(correct_sentence.split())
data.loc[data["id"] == 125627, "word_count"] = word_count
data.loc[data["id"] == 125627, "normalized_text"] = correct_sentence

The only one missing is Gulliver Dark's sentence. After checking the epsiode, we have found no appearence of the character. This means that this is most likely a background song the character is singing and not really a line in the show.
We will delete this row

In [ ]:
data = data[data['id'] != 156870]

# 4 Deleting Group characters

With the previous processing step we realized that there are instances that don't identify charaters but groups of them. For the purpose of this assignemnt we want to focus only on the indviduall characters and therefore will delete all other instances, that augment the size of our dataset without providing any value

In [61]:
data['raw_character_text'].unique().tolist()

['Miss Hoover',
 'Lisa Simpson',
 'Edna Krabappel-Flanders',
 'Martin Prince',
 'Bart Simpson',
 'Landlady',
 'Nelson Muntz',
 'Terri/sherri',
 'Milhouse Van Houten',
 'Wendell Borton',
 'Kid Reporter',
 'Conductor',
 'BERGSTROM',
 'Homer Simpson',
 'Marge Simpson',
 'Ned Flanders',
 'Moe Szyslak',
 'Barney Gumble',
 'Dr. Julius Hibbert',
 "Husband Of Marge's Friend",
 'Maude Flanders',
 'Sophisticate #1',
 'Sophisticate #2',
 'Sophisticate #3',
 'Rev. Timothy Lovejoy',
 'Sultan',
 'Grampa Simpson',
 'Worm Man',
 'HELEN',
 'Gloria',
 'John',
 'Captain',
 'Otto Mann',
 'Convict',
 'Helen Lovejoy',
 'Customer',
 'Ticket Seller',
 'DIAMOND JOE',
 'Jimbo Jones',
 'Lost And Found Guy',
 'Radioactive Man',
 'Fallout Boy',
 'Announcer',
 'Convention Director',
 'BUDDY',
 'Dealer',
 'Young Patty',
 'Young Selma',
 'Older Patty',
 'Older Selma',
 'Mrs. Glick',
 'Adult Narrator',
 'Apu Nahasapeemapetilon',
 'Teller',
 'Eddie',
 'Lou',
 'Asa',
 'Soap Actress',
 'Soap Actor',
 'Mayor Joe Quimby',
 'Waylon Smithers',
 'C. Montgomery Burns',
 'Carl Carlson',
 'Lenny Leonard',
 'Smitty',
 'Osvaldo',
 'Mail Person',
 'Roman',
 'Postal Worker',
 'Joey',
 'Krusty the Clown',
 'Guard #1',
 'Guard #2',
 'Dr. Marvin Monroe',
 'Host',
 'Psychiatrist',
 'Orderly',
 'MICHAEL',
 'Michael',
 'Floyd',
 'Chief Wiggum',
 "Bart's Head",
 'Wiseguy',
 'Voice On Phone',
 'Doctor',
 'Dave',
 'Kearney Zzyzwicz',
 'Snake Jailbird',
 'Bill',
 'Marty',
 'Kent Brockman',
 'Woman',
 'Leon Kompowsky',
 'TV Announcer',
 'Troy McClure',
 'Miss Crowley',
 'Minnesota Girl',
 'Alabama Boy',
 'QUEENS BOY',
 'Jasper Beardly',
 'Female Judge',
 'Dad',
 'Flight Attendant',
 'Man #1',
 'Pilot',
 'Irs Man',
 'Hotel Guest',
 'Truong/maria',
 'MARIA',
 'BARBARA',
 'Worker',
 'Guide',
 'Lobbyist',
 'Arnold',
 'Secretary',
 'Man #2',
 'Newlywed Wife',
 'White Trash Woman #1',
 'Man #3',
 'Old Timer',
 'Thomas Jefferson',
 'Guy',
 'Songster',
 'Page',
 'Senator',
 'Oil Developer',
 'Agent',
 'Speaker',
 'Majority Leader',
 'Everyone Else',
 'President',
 'Foreign Dignitary',
 'TRUONG',
 'Paper Boy',
 'Sportscaster #1',
 'Girl',
 'Neighborhood Guy',
 'Akira',
 'Homemaker',
 'Landscaper',
 'Choreographer',
 'George Washington',
 'Video Voice',
 'DOLPH',
 'Man Shopper',
 "HOMER (CONT'D",
 'Man',
 'Collection Agent',
 'Rod Flanders',
 'Todd Flanders',
 'Wife',
 'Shoppers',
 'Ralph Wiggum',
 'Seymour Skinner',
 'Executive',
 'Fat Tony',
 'Legs',
 'Louie',
 'Race Announcer',
 'Delivery Man',
 'Reporter',
 'Jack Larson',
 'Fbi Agent #1',
 'Fbi Agent #2',
 'Rival Gang Leader',
 'Groundskeeper Willie',
 'Psychic',
 'Lewis Clark',
 'Richard',
 'Skinner Body',
 'Lionel Hutz',
 'Blue-Haired Lawyer',
 'Judge Snyder',
 'Prosecuting Attorney',
 'Joe',
 'Neil',
 'Sherri Mackleberry',
 'Terri Mackleberry',
 'Calm Woman',
 'Mr. Devereaux',
 'Margarita',
 'Program Voices',
 'Instructor',
 'Professor Jonathan Frink',
 'Female Worker',
 'Male Worker',
 'Contestant',
 'Magic Johnson',
 'Luann Van Houten',
 'Aristotle',
 'Patient',
 'Thought Bubble Barney',
 'Female Voice',
 'SCOTT',
 'Security Guard',
 'Miss Lois Pennycandy',
 'Sexy Female Recording',
 'Larry',
 'PENNYCANDY',
 'Rabbi Hyman Krustofsky',
 'Rabbi #1',
 'Rowdy Rabbi',
 'Martian',
 'D.J.',
 'Caller',
 'MONSIGNOR DALEY',
 'Yiddle',
 'Rabbi #2',
 'Waitress',
 'Stagehand',
 'Merchant',
 'Airport Announcer',
 'Customs Agent',
 "Maitre D'",
 'Woman #1',
 'Woman #2',
 'English Diplomat',
 'Argentine Diplomat',
 'Kodos',
 'Kang',
 'Colonel',
 'Female Office Worker',
 'Male Office Worker',
 'Narrator',
 'Townspeople',
 'Patrons',
 'Vin Scully',
 'Kids In Audience',
 'DR MONROE',
 'BART & LISA',
 'Crypt Keeper Willie',
 'Robot',
 'Tv Host',
 'Homer-Ape',
 'Little Man',
 'Lunchlady Doris',
 'Chuck',
 'Teenager',
 'Baby Lisa',
 'Salesclerk',
 'Millicent',
 'Female Clerk',
 'Kevin',
 'Princess Kashmir',
 'Johnny Carson',
 'Dr. Nick Riviera',
 'Audience',
 'Patty Bouvier',
 'Selma Bouvier',
 'Scoey',
 'Teenage Clerk',
 'Football Announcer',
 'Gulliver Dark',
 'DAVE JR.',
 'Official',
 'Voice From Trunk',
 'Weasel #1',
 'British Commentator',
 'P.A. Announcer',
 'Ronnie',
 'DREDERICK',
 'JANEY',
 'Wanda',
 'Becky',
 'Girls',
 'HARV',
 'Patron #1',
 'Patron #2',
 'Collette',
 'Bernard',
 'Photographer',
 'Aide',
 'Aerosmith',
 'Steven Tyler',
 'Joe Perry',
 'Crowd',
 'Brad Whitford',
 'HUGH',
 'Everyone',
 'Bartender',
 'One-eyed Bartender',
 'Flowers',
 'Tom Hamilton',
 'Joey Kramer',
 'Snappy',
 'Broker',
 'Scott Christian',
 'Hans',
 'Fritz',
 'Charlie',
 'Horst',
 'German Teacher',
 'Boxer',
 'Barflies',
 'Mr. Thorson',
 'Mother',
 'Angel',
 'Clerk',
 'Justice Of The Peace',
 'Groom',
 'Applicant #1',
 'Applicant #2',
 'Applicants',
 'Tourist Kid',
 'Tourist Dad',
 'Boss',
 'Elderly Lady',
 'Repo Man',
 'Driver',
 'M.C.',
 'Boy',
 'Operator',
 'Barber',
 'Rosarita',
 'Kids',
 'Weasel',
 'Robot Weasel',
 'Señor Beaver-otti',
 'Robot Animals',
 'Dave Shutton',
 'Fat Cop',
 'Falcon Man',
 'Sailor',
 'Sting',
 'Sideshow Mel',
 'Choir',
 'Souvenir Hawker',
 'Station Announcer',
 'Old Lady #1',
 'Bret',
 'JIMMY',
 'Sportscaster',
 'Coach',
 'Football Announcer #2',
 'Player',
 'Librarian',
 'Marco',
 'Box',
 'UGOLIN',
 'Nutty Comedian',
 'Cesar',
 'Alien',
 'Duff Announcer',
 'Nick',
 'Nick #2',
 'Commercial Guy',
 'Man On Phone',
 'Bus Driver',
 'Arnie Pye',
 'Policewoman',
 'Track Announcer',
 'Ozzie Smith',
 'Different Announcer',
 'Chef Rodrigo',
 'Gregory',
 'FABRIZIO',
 'Voice',
 'Woman On Tv #1',
 'Woman On Tv #2',
 'Teenage Boy',
 'CHIF WIGGUM',
 'Service Manager',
 'Ted',
 'Sound-alikes',
 'Mister Amazing',
 'Sparkle',
 'Romantic Lover Voice',
 'Southern Private',
 'Charles Boyer',
 'Umpire',
 'Dispatcher',
 'ARI',
 'Jose Canseco',
 'Mike Scioscia',
 'Tour Guide',
 'Don Mattingly',
 'Steve Sax',
 'Roger Clemens',
 'Wade Boggs',
 'KEN GRIFFEY JR.',
 'Darryl Strawberry',
 'Hypnotist',
 'ALL THE PLAYERS',
 'Nurse',
 'JOSE CONSECO',
 'Ticket Taker',
 'Courier',
 'Attendant',
 'Dr. J. Loren Pyror',
 'FORTE',
 'Sylvia Winfield',
 'Donna',
 'Tammy',
 'PRINCIPAL WILLIE',
 'Prosecutor',
 'Steve Allen',
 'Mr. Montone',
 'Former Teacher',
 'Teacher #1',
 'Teacher #2',
 'Hippie Teacher',
 'Employee',
 'Employer',
 'Window Washers',
 'Sanjay Nahasapeemapetilon',
 'Lottery Announcer',
 'Vet',
 'Mr. Danielson',
 'God',
 'Sadistic Barfly',
 'Young Barfly',
 'Trainee',
 'Ticket Man',
 'Butler',
 'General',
 'Cowboy #1',
 'Cowboy #2',
 'Bar Owner',
 "Yodelin' Zeke",
 'Lurleen Lumpkin',
 'Male Nurse',
 'Music Store Owner',
 'Salesman',
 'Mr. Boylan',
 'Mule',
 'Young Girl',
 'Pretty Girl',
 'Orville',
 'Hurley',
 'Dinosaur Dad',
 'Dinosaur Son',
 'Sideshow Bob',
 'Cellmate #1',
 'Guard',
 'Kindly Old Gent',
 'Crooner',
 'MacGyver',
 'T-shirt Guy',
 'Promoter',
 'Comic Book Guy',
 'David',
 'Nigel Bakerbutcher',
 'DEREK',
 'Roadie',
 'Stoned Guy',
 'DAVID/NIGEL',
 'DAVID/NIGEL/DEREK',
 'Manager',
 'Landlord',
 'Samantha Stanky',
 'Grave Digger',
 'Crane Operator',
 'Female Announcer',
 'Worker #1',
 'Worker #2',
 'Mr. Stanky',
 'Kirk Van Houten',
 'Nun',
 'NUN #2',
 'Lawyer',
 'Bum',
 'HERB',
 'WILLIAM POWEL LOOKALIKE',
 'Bum #2',
 'Nbc Anchorman',
 'Jittery Private',
 'Angry Sergeant',
 "Smokin' Joe Frazier",
 'Herb Powell',
 'Mom',
 'Radio Announcer',
 'Students',
 'Teachers',
 'Teacher',
 'Martin Prince, Sr.',
 'Mr. Black',
 'Sergeant',
 'Campers',
 'Line Judge',
 'Stablehand',
 'Kid',
 'Little Girl',
 'Little Boy #1',
 'Queen Elizabeth II',
 'Yoga Instructor',
 "HOMER'S THOUGHT",
 'Contestants',
 'Mr. Bozwell',
 'DEBORAH JO SMALLWOOD',
 'Llewellyn Sinclair',
 'Auditioning Woman #1',
 'Auditioning Woman #2',
 'Auditioning Woman #3',
 'Ms. Sinclair',
 'Nerd #1',
 'Video Game Voice',
 'Krusty Doll',
 'Company',
 'Actress',
 'Nerd #2',
 'Male Parishoner',
 'Stooge #1',
 'Stooge #2',
 'Boring Guy',
 'Commentator',
 'Abraham Lincoln',
 'Flanders Family',
 'Jamshed',
 'Insurance Agent',
 'Benjamin Franklin',
 'Barker',
 'Booth Man',
 'Caricaturist',
 'Small Voice',
 'Tv Father',
 'Tv Daughter',
 'Bitsy',
 'Ramona',
 'Owner',
 'Amber Dempsey',
 'Ice Cream Lady',
 'Pahasatira',
 'Judges',
 'Museum Worker',
 'Show Announcer',
 'Bob Hope',
 'Advance Man',
 'Soldier #1',
 'Soldier #2',
 'Santa Claus',
 'Football Player',
 'Shopkeeper',
 'Gangster',
 'Repairman',
 'Sailor #1',
 'Sailor #2',
 'Natives',
 "'30s Reporter",
 'Girl Star',
 'Co-pilot',
 'Usher',
 'Jacqueline Bouvier',
 'Faces',
 'Zombies',
 'Skinner Zombie',
 'Zombie Krusty',
 'Zombie Flanders',
 'Zombie Shakespeare',
 'Lisa Snail',
 'Zombie',
 'Pilgrim Zombie',
 'Cowboy Zombie',
 'Helmsman',
 'Chief Engineer',
 'Rowdy Woman',
 'Bumblebee Man',
 'Itchy',
 'Astronaut',
 'Booth Attendant',
 'MCCLURE',
 'Contractor',
 'Headless Brakeman',
 'Marley',
 'Donut Man',
 'Tom Jones',
 'Animal Handler',
 'Homer',
 'Hunk',
 'Price',
 'Laura Powers',
 'Squeaky-Voiced Teen',
 'Mrs. Powers',
 'Guy #1',
 'Guy #2',
 'Waiter',
 'Chef',
 'Waiter #2',
 'Old Man',
 'Attorney',
 'Mailman',
 'Delivery Boy',
 'Fat Foreman',
 'RICARDO',
 'Alan Thicke',
 'Adjuster',
 'Farmer',
 'Model',
 'Second Man',
 'German Engineer',
 'Adam West',
 'President Bush',
 '"Just Stamp the Ticket" Man',
 'Captain Horatio McCallister',
 'Teenage Barney',
 'Linda Ronstadt',
 'Copy Writer',
 'Cameraman',
 'Bigfoot',
 'Mountain Goat',
 'Fruit Vendor',
 'Irish Lady',
 'Italian Lady',
 'Talk Show Host',
 'Sidekick',
 'Realtor',
 'Director',
 'Ad Man',
 'Female Messenger',
 'Clown Bed',
 'Old Woman',
 'Korean Gymnast',
 'Maggie Simpson',
 'Pig',
 'Hans Moleman',
 'Gas Station Boy',
 'Billy',
 "Homer's Spirit",
 'INTERCOM',
 'Reporters',
 'Sunday School Teacher',
 'VIDEO TAPE NARRATOR',
 'Pumpkin Man',
 'Med Students',
 'Handsome Young Man',
 'Andre',
 'Young Riviera',
 'Angry Man',
 'Warrior',
 'LANLEY',
 'Truckosaurus',
 'Sebastian Kobb',
 'Woman With Baby',
 'NIMOY',
 'Engineer #1',
 'Engineer #2',
 'Haverbrook Man',
 'Bart Anchor',
 'Lance Murdock',
 '2nd Announcer',
 "Homer's Thought Bubble",
 'Reverend',
 "Aunt Gladys's Corpse",
 'Aunt Gladys',
 "HUTZ' VOICE",
 'MR. HUTZ',
 'Interviewer',
 'Princess Opal',
 'Bag Boy',
 'Cashier',
 'Waitress #2',
 'Sperm Doctor',
 'MAN ON RADIO',
 'Surly',
 'Attractive Woman',
 'Man On Tv',
 'Beer Singers',
 'Security Man',
 'Washington',
 'Man In White Coat',
 'Boys',
 "Santa's Little Helper",
 "Homer's Bloody Skull",
 'Sketch Announcer',
 'Agency Worker',
 'TOM',
 'Fans',
 'Small Man',
 'Chihuahua',
 'Cat',
 'Corey',
 'Pepi',
 "Apu's Brain",
 'JOHNNY',
 'Truck Driver',
 'Rex',
 "Homer's Conscience",
 'Robert Frost',
 'FROST',
 'Raheem',
 'Presidents',
 'Harrison',
 "Presidents' Heads",
 'Teddy Roosevelt',
 '3rd World Father',
 '3rd World Family',
 'Tourists',
 'Cartoon Doctor',
 'Richard Nixon',
 'Kennedy',
 'Mrs. Phillips',
 'Assembly',
 "Chuck's Dad",
 'Parent One',
 'Parent Two',
 'Feminists',
 'Baseball Announcer',
 'Train',
 'Dr. Wolfe',
 'Senator Mendoza',
 'Receiver',
 "Burns' Grandfather",
 'Mc',
 'Workers',
 'Gummy Joe',
 'Donut Vendor',
 'Mop Top #1',
 'Mop Top #2',
 'Mop Top #3',
 'Mop Tops',
 'Goon',
 'Quigley',
 'Robots',
 'DR. JOYCE',
 'Pagan Simpsons',
 'Waiters/cooks',
 'Specialist',
 'Another Worker',
 'Intern',
 'Scratchy',
 'Elvis',
 'Writer',
 'Roxie',
 "Bart's Thoughts",
 "Lisa's Thoughts",
 'Principal Dondelinger',
 'Bobby Mindich',
 'ARTIE',
 "Barney's Boss",
 'Writer #2',
 'BROOKE',
 "Homer's Brain",
 'Child',
 'Gary Chalmers',
 'Scottish Woman',
 'Exhaust Pipe Lid',
 'Chicken',
 'Mr. Ogden',
 'Hitler',
 'Scientist #1',
 'Scientist #2',
 'Evil Homer',
 'Recruiter',
 'Actor',
 'Teenaged Guide',
 "Children's Choir",
 'Boy Soloist',
 'Driver Of Foreign Car',
 'Barry White',
 'Miss Springfield',
 'Dewey Largo',
 'Irishman',
 'Old Mrs. Glick',
 'SICK JAPANESE WORKER',
 'Japanese Worker #2',
 'White Blood Cell #1',
 'White Blood Cell #2',
 'Virus',
 'JAMAICAN MAN',
 'Mob',
 'Husband',
 'Policeman',
 'Jury',
 'David Crosby',
 'Jury Foreman',
 'Bailiff',
 'Warden',
 'Phillips',
 'Tattoo Annie',
 'Park Commissioner',
 'Assistant',
 'Jacqueline',
 'Rainier Wolfcastle',
 'Coast Guard Officer',
 'Charley Weaver',
 'Gabbo',
 'CRANDALL',
 'Soldier Puppets',
 'Cossack Puppets',
 'Alphonse',
 'Commercial Announcer',
 'Casting Director',
 'Old Man Singers',
 'Bette Midler',
 'Hugh Hefner',
 'Anthony Kiedis',
 'Flea',
 'Elizabeth Taylor',
 'Newsman',
 'Counter Boy',
 'Mr. Johannson',
 'Stage Manager',
 'Luke Perry',
 'Chad Smith',
 'ARIK MARSHAL',
 'Krusty Announcer',
 'Man At Table',
 'Herman Hermann',
 'SPEEDED UP VOICES',
 'Melvin',
 'All',
 'Be Sharps',
 'Quartet',
 'Reporter #2',
 'Tenor',
 'Paul Harvey',
 'Reporter #3',
 'Reporter #1',
 'Ronald Reagan',
 'Panicky Man',
 'Sarah Wiggum',
 'Female Talk Show Host',
 'George Harrison',
 '2-Year-Old Lisa',
 'Teenage Bellboy',
 'Surly Man',
 'Kako',
 'Human Fly',
 'Sinister Male Voice',
 'Schoolyard Girls',
 'MRS KRABAPPEL',
 'Parole Board Head',
 'People In Court',
 'Parole Board Member #1',
 'Parole Board',
 'Parole Board Member #2',
 'Man On Screen',
 'Woman On Tape',
 'Investigator',
 'Celestial Choir',
 "Woman's Voice",
 'Nrc Woman',
 'Nrc Man',
 'Dumb Employee #1',
 'Dumb Employee #2',
 'Scholar',
 'Counselor',
 'Admissions Man',
 'Admissions Woman',
 'Hillbilly Man',
 'Angry Dean',
 'Nerdlinger',
 'Jock',
 'Skinny Student',
 'Dean Bobby Peterson',
 'Professor',
 'Foreman',
 'Architect',
 'Men',
 'Dean',
 'Doug',
 'Gary',
 'Benjamin',
 'Automated Voice',
 'Guards',
 '7-YEAR OLD BURNS',
 "Burns' Mother",
 "Burns's Father",
 'George Burns',
 'Jimmy Carter',
 'George H.W. Bush',
 'RAMONE #1',
 'RAMONE #2',
 'RAMONE #3',
 'RAMONE #4',
 'Drummer',
 'Mechanic',
 'Explorer',
 'Bear',
 'Hooded Man',
 'Workman',
 'Workman #2',
 'Dinosaur',
 'Mr. Boswell',
 'Devil',
 'Pieces Of Homer',
 'Demon Technician',
 'Skeleton Judge',
 'Blackbeard',
 'Benedict Arnold',
 'Lizzie Borden',
 'KODO',
 'Exchange Student',
 'GROUNDKEEPER WILLIE',
 'Humorist',
 'Edward',
 'The Pope',
 'RUTH',
 'Scientist',
 'Technician #1',
 'Technician #2',
 'Tough Guy',
 'Lady',
 'Tape Player',
 "Lenny's Wife",
 'Mohawk Girl',
 'Woman #3',
 'Woman #4',
 'Fry Cook',
 'Diner Owner',
 'GOODMAN',
 "Flanders' Inner Child",
 "Homer's Inner Child",
 "Moe's Inner Child",
 'Women In Crowd',
 'Old Folks',
 'MR. KRABAPPEL',
 'James Brown',
 'Carpenter',
 'Dorky Teenager',
 'Vendor',
 'MCGARNIGAL',
 'Atari Andre Gregory',
 'Manuel Noriega',
 'Security Guard #1',
 'Arcade Manager',
 'Wise Old Hobo',
 'Triple Milhouse',
 'Dorky Kid',
 'Pudgy Boy',
 'Fathers',
 'Ernest Borgnine',
 'Accountant',
 'Arab Men',
 'Agent #1',
 'Zutroy',
 'Agent #2',
 'Optometrist',
 'Dermatologist',
 'Podiatrist',
 'Internist',
 'Jerry Lewis Bart',
 'Mindy',
 'Cherub Lenny',
 'Cherub Carl',
 'Fish',
 'Sexy Woman Announcer',
 'Jeeves',
 'WHITE HOUSE AIDE',
 'Turban Kid',
 'Fat Kid',
 'Nerds',
 'Big Hand Man',
 'Bellhop',
 'Passerby #1',
 'Passerby #2',
 'Chinese Waiter #1',
 'Chinese Waiter #2',
 'Newsreel Announcer',
 'Amos Guy',
 'Young Jasper',
 'Panhandler',
 'Angry Voice From Stall',
 'Henry Kissinger',
 "HENRY KISSINGER'S BRAIN",
 'Female Executive',
 'British Guy',
 'British Waitress',
 'Hippie',
 'Gerry Cooney',
 'BIG TEXAN',
 'Croupier',
 'Ernst',
 'Gunter',
 'Teenage Attendant',
 'Someone',
 'Rain Man',
 'Gambler',
 'CRAP PLAYERS',
 'Farmboy',
 'Slot Player #1',
 'Slot Player #2',
 'Audience Member',
 'Wheelman',
 'Robert Goulet',
 'Molloy',
 'Voice From The Back',
 'IRISH PETE',
 'Beatnik Poet',
 'Twelve-year-old',
 'Student',
 'Cat Burglar',
 'Box Executive',
 'Organ Grinder',
 'Crowd Member',
 '2nd Crowd Member',
 'Mrs. Quimby',
 'Fireman',
 'Hammer',
 'CONAN',
 'Kitty',
 'Customer #1',
 'Customer #2',
 'Technician',
 'Bum #1',
 'Comedian',
 'James Woods',
 'Stockboy',
 'Christians',
 'Robed Indian',
 'Aged Man',
 ...]

# 5 Simplifying labels

# 3 Irrelevant Columns

there are a few columns that are also irrelevant for our use case.
* timestamp_in_ms -> we don't care about the moment in the episode the character speaks
* location_id -> we don't care about location
* raw_location_text -> same as the one above
* raw_text -> same as normalized text and spoken words, but adds noise such as emotions between brackets, which we are not interested in this assingment and make processing more complicated
* spoken_words -> it's repetitive having it's normalized version 

We can delete this columns

In [47]:
data.drop(columns = ['timestamp_in_ms','location_id','raw_location_text','raw_text','spoken_words'],inplace=True)

In [48]:
data

,id,episode_id,number,character_id,raw_character_text,normalized_text,word_count
0,9549,32,209,464.0,Miss Hoover,no actually it was a little of both sometimes ...,31
1,9550,32,210,9.0,Lisa Simpson,wheres mr bergstrom,3
2,9551,32,211,464.0,Miss Hoover,i dont know although id sure like to talk to h...,22
3,9552,32,212,9.0,Lisa Simpson,that life is worth living,5
4,9553,32,213,40.0,Edna Krabappel-Flanders,the polls will be open from now until the end ...,33
...,...,...,...,...,...,...,...
158266,9544,32,204,464,Miss Hoover,im back,2
158267,9545,32,205,464,Miss Hoover,you see class my lyme disease turned out to be,10
158268,9546,32,206,464,Miss Hoover,psy-cho-so-ma-tic,1
158269,9547,32,207,119,Ralph Wiggum,does that mean you were crazy,6
158270,9548,32,208,4,JANEY,no that means she was faking it,7

# 4 Adding Season and number in season

we don't have a clear column indicating the season the epsiodes belong to, even though they can be deuced from the epsiode_id column, which indicates the epsiode without distingushing between seasons.
Since maaping this epsidoes to their respective seasons would requiere manually checking each one of them, we can use the dataset of the previous assingment that already has a defined 'season' column to create the column in our dataset

Since for the clean version of the dataset of the previous assignment we deleted all epsiodes of the last available season (it only had 4 episdes) to help our interests, we won't use this version for this assingment since we can use that information. We will read the raw one

In [49]:
data_seasons = pd.read_csv('../data/simpsons_episodes_raw.csv')[['season','number_in_season','number_in_series']]

In [50]:
episodes_daat1 = set(data['episode_id'])
episodes_data2 = set(data_seasons['number_in_series'])
episodes_daat1 - episodes_data2

set()

we see that all epsiodes in our script lines dataset are in the datset from the previous quarter

In [51]:
print(episodes_data2 - episodes_daat1)
len(episodes_data2 - episodes_daat1)

{550, 424, 569, 441, 570, 571, 572, 573, 575, 576, 577, 578, 579, 580, 581, 582, 583, 574, 447, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600}

36

However this is not true when inverting the order, the dataset from the previous assignment has 32 more episodes. The second source used on the previous assignment also has this same issue. We explored extra datasets such as this one: https://github.com/jcrodriguez1989/thesimpsons or https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-02-04/readme.md but to no success. No datasets contained the missing epsiodes

In [52]:
data = data.merge(data_seasons, left_on='episode_id', right_on='number_in_series', how='left')
data.drop(columns=['number_in_series'], inplace=True)
# put season before episode_id
cols = data.columns.tolist()
cols.insert(cols.index('episode_id'), cols.pop(cols.index('season')))
cols.insert(cols.index('episode_id'), cols.pop(cols.index('number_in_season')))
data = data[cols]
data

,id,season,number_in_season,episode_id,number,character_id,raw_character_text,normalized_text,word_count
0,9549,2,19,32,209,464.0,Miss Hoover,no actually it was a little of both sometimes ...,31
1,9550,2,19,32,210,9.0,Lisa Simpson,wheres mr bergstrom,3
2,9551,2,19,32,211,464.0,Miss Hoover,i dont know although id sure like to talk to h...,22
3,9552,2,19,32,212,9.0,Lisa Simpson,that life is worth living,5
4,9553,2,19,32,213,40.0,Edna Krabappel-Flanders,the polls will be open from now until the end ...,33
...,...,...,...,...,...,...,...,...,...
132048,9544,2,19,32,204,464,Miss Hoover,im back,2
132049,9545,2,19,32,205,464,Miss Hoover,you see class my lyme disease turned out to be,10
132050,9546,2,19,32,206,464,Miss Hoover,psy-cho-so-ma-tic,1
132051,9547,2,19,32,207,119,Ralph Wiggum,does that mean you were crazy,6
132052,9548,2,19,32,208,4,JANEY,no that means she was faking it,7

# 5 Renamiming to keep columns undestandable

column number identifies the line within each, season. We find this name rather confusing, we'll change it to one that explains the variable better

In [54]:
data.rename(columns={'number': 'line_number_in_episode'}, inplace=True)  
data[data['episode_id'] ==  28]

,id,season,number_in_season,episode_id,line_number_in_episode,character_id,raw_character_text,normalized_text,word_count
123021,8143,2,15,28,4,1114,McBain,only your death,3
123022,8145,2,15,28,6,1114,McBain,meeting adjourned,2
123023,8150,2,15,28,11,1114,McBain,right now im thinking about holding another me...,10
123189,8205,2,15,28,66,31,Young Grampa,okay,1
123190,8207,2,15,28,68,31,Young Grampa,i promise,2
...,...,...,...,...,...,...,...,...,...
131130,8501,2,15,28,362,31,Grampa Simpson,i knew youd blow it,5
131131,8504,2,15,28,365,8,Bart Simpson,dad,1
131132,8505,2,15,28,366,2,Homer Simpson,what is it boy,4
131133,8506,2,15,28,367,8,Bart Simpson,i thought your car was really cool,7
131134,8507,2,15,28,368,2,Homer Simpson,thanks boy i was waiting for someone to say that,10

In [55]:
data

,id,season,number_in_season,episode_id,line_number_in_episode,character_id,raw_character_text,normalized_text,word_count
0,9549,2,19,32,209,464.0,Miss Hoover,no actually it was a little of both sometimes ...,31
1,9550,2,19,32,210,9.0,Lisa Simpson,wheres mr bergstrom,3
2,9551,2,19,32,211,464.0,Miss Hoover,i dont know although id sure like to talk to h...,22
3,9552,2,19,32,212,9.0,Lisa Simpson,that life is worth living,5
4,9553,2,19,32,213,40.0,Edna Krabappel-Flanders,the polls will be open from now until the end ...,33
...,...,...,...,...,...,...,...,...,...
132048,9544,2,19,32,204,464,Miss Hoover,im back,2
132049,9545,2,19,32,205,464,Miss Hoover,you see class my lyme disease turned out to be,10
132050,9546,2,19,32,206,464,Miss Hoover,psy-cho-so-ma-tic,1
132051,9547,2,19,32,207,119,Ralph Wiggum,does that mean you were crazy,6
132052,9548,2,19,32,208,4,JANEY,no that means she was faking it,7

In [ ]:
data.to_csv('../data/simpsons_script_lines_cleaned.csv', index=False)